// ====================== QUIZ ======================

// Create Quiz
export const CREATE_QUIZ_REQUEST = "CREATE_QUIZ_REQUEST";
export const CREATE_QUIZ_SUCCESS = "CREATE_QUIZ_SUCCESS";
export const CREATE_QUIZ_FAILURE = "CREATE_QUIZ_FAILURE";

// Add Question to Quiz
export const ADD_QUESTION_REQUEST = "ADD_QUESTION_REQUEST";
export const ADD_QUESTION_SUCCESS = "ADD_QUESTION_SUCCESS";
export const ADD_QUESTION_FAILURE = "ADD_QUESTION_FAILURE";


export const UPDATE_QUIZ_REQUEST = "UPDATE_QUIZ_REQUEST";
export const UPDATE_QUIZ_SUCCESS = "UPDATE_QUIZ_SUCCESS";
export const UPDATE_QUIZ_FAILURE = "UPDATE_QUIZ_FAILURE";

// Get Quiz by ID
export const GET_QUIZ_BY_ID_REQUEST = "GET_QUIZ_BY_ID_REQUEST";
export const GET_QUIZ_BY_ID_SUCCESS = "GET_QUIZ_BY_ID_SUCCESS";
export const GET_QUIZ_BY_ID_FAILURE = "GET_QUIZ_BY_ID_FAILURE";

// Get Quizzes by Program
export const GET_QUIZZES_BY_PROGRAM_REQUEST = "GET_QUIZZES_BY_PROGRAM_REQUEST";
export const GET_QUIZZES_BY_PROGRAM_SUCCESS = "GET_QUIZZES_BY_PROGRAM_SUCCESS";
export const GET_QUIZZES_BY_PROGRAM_FAILURE = "GET_QUIZZES_BY_PROGRAM_FAILURE";

// Create Quiz
export const DELETE_QUIZ_REQUEST = "DELETE_QUIZ_REQUEST";
export const DELETE_QUIZ_SUCCESS = "DELETE_QUIZ_SUCCESS";
export const DELETE_QUIZ_FAILURE = "DELETE_QUIZ_FAILURE";

// ====================== QUIZ SUBMISSION ======================

// Submit Quiz
export const SUBMIT_QUIZ_REQUEST = "SUBMIT_QUIZ_REQUEST";
export const SUBMIT_QUIZ_SUCCESS = "SUBMIT_QUIZ_SUCCESS";
export const SUBMIT_QUIZ_FAILURE = "SUBMIT_QUIZ_FAILURE";

// Get User Submissions
export const GET_SUBMISSIONS_BY_USER_REQUEST = "GET_SUBMISSIONS_BY_USER_REQUEST";
export const GET_SUBMISSIONS_BY_USER_SUCCESS = "GET_SUBMISSIONS_BY_USER_SUCCESS";
export const GET_SUBMISSIONS_BY_USER_FAILURE = "GET_SUBMISSIONS_BY_USER_FAILURE";

// Save user's answers periodically
export const SAVE_QUIZ_PROGRESS_REQUEST = "SAVE_QUIZ_PROGRESS_REQUEST";
export const SAVE_QUIZ_PROGRESS_SUCCESS = "SAVE_QUIZ_PROGRESS_SUCCESS";
export const SAVE_QUIZ_PROGRESS_FAILURE = "SAVE_QUIZ_PROGRESS_FAILURE";

// Get user's in-progress attempt when loading a quiz
export const GET_IN_PROGRESS_ATTEMPT_REQUEST = "GET_IN_PROGRESS_ATTEMPT_REQUEST";
export const GET_IN_PROGRESS_ATTEMPT_SUCCESS = "GET_IN_PROGRESS_ATTEMPT_SUCCESS";
export const GET_IN_PROGRESS_ATTEMPT_FAILURE = "GET_IN_PROGRESS_ATTEMPT_FAILURE";