// 🔹 Student - Get all programs
export const GET_PROGRAMS_REQUEST = "GET_PROGRAMS_REQUEST";
export const GET_PROGRAMS_SUCCESS = "GET_PROGRAMS_SUCCESS";
export const GET_PROGRAMS_FAILURE = "GET_PROGRAMS_FAILURE";

// 🔹 Student - Get one program detail
export const GET_PROGRAM_REQUEST = "GET_PROGRAM_REQUEST";
export const GET_PROGRAM_SUCCESS = "GET_PROGRAM_SUCCESS";
export const GET_PROGRAM_FAILURE = "GET_PROGRAM_FAILURE";

// 🔹 Admin - Create
export const CREATE_PROGRAM_REQUEST = "CREATE_PROGRAM_REQUEST";
export const CREATE_PROGRAM_SUCCESS = "CREATE_PROGRAM_SUCCESS";
export const CREATE_PROGRAM_FAILURE = "CREATE_PROGRAM_FAILURE";

// 🔹 Admin - Update
export const UPDATE_PROGRAM_REQUEST = "UPDATE_PROGRAM_REQUEST";
export const UPDATE_PROGRAM_SUCCESS = "UPDATE_PROGRAM_SUCCESS";
export const UPDATE_PROGRAM_FAILURE = "UPDATE_PROGRAM_FAILURE";

// 🔹 Admin - Delete
export const DELETE_PROGRAM_REQUEST = "DELETE_PROGRAM_REQUEST";
export const DELETE_PROGRAM_SUCCESS = "DELETE_PROGRAM_SUCCESS";
export const DELETE_PROGRAM_FAILURE = "DELETE_PROGRAM_FAILURE";

// 🔹 Student - Enroll
export const ENROLL_PROGRAM_REQUEST = "ENROLL_PROGRAM_REQUEST";
export const ENROLL_PROGRAM_SUCCESS = "ENROLL_PROGRAM_SUCCESS";
export const ENROLL_PROGRAM_FAILURE = "ENROLL_PROGRAM_FAILURE";

// 🔹 Student - Unenroll
export const UNENROLL_PROGRAM_REQUEST = "UNENROLL_PROGRAM_REQUEST";
export const UNENROLL_PROGRAM_SUCCESS = "UNENROLL_PROGRAM_SUCCESS";
export const UNENROLL_PROGRAM_FAILURE = "UNENROLL_PROGRAM_FAILURE";

// 🔹 Student - My enrollments
export const GET_ENROLLED_PROGRAMS_REQUEST = "GET_ENROLLED_PROGRAMS_REQUEST";
export const GET_ENROLLED_PROGRAMS_SUCCESS = "GET_ENROLLED_PROGRAMS_SUCCESS";
export const GET_ENROLLED_PROGRAMS_FAILURE = "GET_ENROLLED_PROGRAMS_FAILURE";

// 🔹 Admin - Get Students
export const GET_STUDENTS_BY_PROGRAM_REQUEST =
    "GET_STUDENTS_BY_PROGRAM_REQUEST";
export const GET_STUDENTS_BY_PROGRAM_SUCCESS =
    "GET_STUDENTS_BY_PROGRAM_SUCCESS";
export const GET_STUDENTS_BY_PROGRAM_FAILURE =
    "GET_STUDENTS_BY_PROGRAM_FAILURE";
